[server]
port=12306

[redis]
enable=false
prefix="qp"
host="192.168.1.8"
password=""
port=31929
maxIdle=3
maxActive=10

[database]
driver="mysql"
host="192.168.1.8"
user="root"
password="root"
db="grab-12306"
port=31964
prefix="t_"
showSql=true

[log]
level="debug"
showCode=true
dir="logs"
rotate=10